import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  globalIgnores([".next", "out", "next-env.d.ts"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs["recommended-latest"],
      jsxA11y.flatConfigs.strict,
      eslintConfigPrettier,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // The a11y floor in CLAUDE.md is a CI gate, not a suggestion.
      "jsx-a11y/no-autofocus": "error",
      "jsx-a11y/anchor-is-valid": "off", // next/link renders a valid anchor

      // A horizontally scrolling container MUST be focusable or its off-screen
      // columns are unreachable by keyboard — axe flags that as
      // scrollable-region-focusable. This rule forbids tabIndex on
      // non-interactive elements by default, which directly contradicts that,
      // so `region` joins the allowlist. Every such container also carries an
      // aria-label, which role="region" requires.
      "jsx-a11y/no-noninteractive-tabindex": [
        "error",
        { tags: [], roles: ["tabpanel", "region"], allowExpressionValues: true },
      ],
    },
  },
  {
    // src/components/ui is vendored shadcn output, regenerated by `shadcn add`.
    // Its Label is a wrapper — association happens at the call site, and call
    // sites ARE linted by the config above. Suppressing here rather than editing
    // generated files means the next `shadcn add` does not reintroduce the error.
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "jsx-a11y/label-has-associated-control": "off",
    },
  },
]);
